Actualización del ReadMe.md
natanfdecastro/PP1_Analizador_Lexico_IC5701 pull request #7
Opened 2020-06-09 23:04 UTC by Emanlui

También se cambió la ruta estática por la carpeta de resources.

2020-06-09 23:24 UTC, natefedez requested changes

2020-06-09 23:24 UTC, natanfdecastro commented on README.md
> +  - Emanuelle Jiménez (Emanlui)
Dos apellidos y quitar el nickname :P

2020-06-09 23:24 UTC, natanfdecastro commented on src/main/Main.py
> +path = os.getcwd().split("\\")
Agregar la documentación interna adecuada para este código nuevo

2020-06-09 23:24 UTC, natanfdecastro commented on src/main/Main.py
> +for i in range(len(path)-1):
Se hicieron las pruebas correspondientes que es funcional en Windows y Linux?

2020-06-09 23:24 UTC, natanfdecastro commented on README.md
> +   - A la hora de utilizar jetbrains para programar debemos buscar la opción de terminal, esta es facilitada por el mismo idle.
Agregar versión de PyCharm utilizada, enlace de descarga y agregar combinación de teclas para editar configuración de corrida o hacerlo de forma manual

2020-06-09 23:24 UTC, natanfdecastro commented on README.md
> +   - A la hora de utilizar jetbrains para programar debemos buscar la opción de terminal, esta es facilitada por el mismo idle.
Cambiar jetbrains -> PyCharm Jetbrains [versión]

2020-06-09 23:24 UTC, natanfdecastro commented on README.md
> +   - En caso de que se utilice linux, entonces se debe escribir el siguiente comando en la terminal:
`linux` empieza en mayúscula

2020-06-09 23:24 UTC, natanfdecastro commented on README.md
> +   - El lenguaje de programación utilizado para crear dicho compilador fue python, es por eso que es necesario instalarlo en el sistema para correr el programa. El instalador se encuentra en el sigui
* `python` empieza en mayúscula, bien hecho al agregar el enlace para instalar `Python`
* Agregar versión de `Python` utilizada

2020-06-09 23:24 UTC, natanfdecastro commented on README.md
> +Este proyecto tiene como finalidad la creación de un analizador léxico de java tropicalizado al español
cambiar a `Java Tropicalizado al Español`

2020-06-09 23:24 UTC, natanfdecastro commented on README.md
> +  - Una vez instalado python3 debemos abrir la terminal de python y correr el siguiente comando
`python` va en mayúscula y especificar siempre la versión de lenguaje utilizado

2020-06-09 23:24 UTC, natanfdecastro commented on README.md
> +# Analizador Léxico
Escribir el nombre del Proyecto como título

2020-06-10 04:06 UTC, Emanlui commented on README.md
> +   - A la hora de utilizar jetbrains para programar debemos buscar la opción de terminal, esta es facilitada por el mismo idle.
Yo no tuve que editar mediante configuración de teclas

2020-06-10 04:43 UTC, natefedez approved these changes

2020-06-10 04:45 UTC, merged